akiyosi/goneovim

editor/workspace.go

Just a demonstration of #27 .
I've tested it and it could be used to connect to a remote session. By using the following command:
```bash
gonvim --server ADDRESS
```
However, the latency is significantly higher than neovim-qt's remote connection for unknown reasons, so it's not really pleasant to work in this configuration.
UPDATE: Previously I said the latency is high because when you move around a file using jk, it seems to be quite slow. However, I found that if I open a `:terminal`, the latency of `jk` is quite okay in the `:terminal` window. So I guess it's caused by some specific feature that is only enabled in normal file window.

allow a `--server` option

---

editor/screen.go

The event itself is from neovim, we do not need to send it back to nvim

No need to send close command on windowClose event

---

cmd/goneovim/darwin/Contents/Info.plist

macOS has the concept of Uniform Type Identifiers[1] which allows to associate an app to a bunch of files. This commit asociates Goneovim to all plain text files.
Go doesn't seem to be recognized by the operating system yet so I kept its definition
[1]:https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis

Add plain.text UTI

---

editor/config.go
editor/editor.go
editor/editor_mac_test.go

This is the equivalent of the `macmeta` configuration in MacVim.
The feature is available by adding the following to `~/.goneovim/setting.toml`
```
[Editor]
Macmeta = true
```
Related issue: #129

Add Macmeta

---

editor/editor.go

Hi - first of all, thank you for you work on this GUI!
when `$XDG_CONFIG_HOME` is set, `goneovim` currently expects its config file `setting.toml` to be inside `$XDG_CONFIG_HOME`. It should instead follow the convention of having its own subdirectory, and look for a file like `$XDG_CONFIG_HOME/goneovim/setting.toml`.
`$XDG_CONFIG_HOME/setting.toml` (the filepath currently searched for) is too generic to be used by `goneovim`.

use goneovim subdirectory inside XDG_CONFIG_HOME

---

README.md

As per [this](https://github.com/Homebrew/homebrew-cask/pull/107483) it's possible to install through homebrew

chore: Add note about homebrew support

---

editor/config.go
editor/cursor.go
editor/editor.go
editor/font.go
editor/imetooltip.go
editor/message.go
editor/minimap.go
editor/notification.go
editor/popupmenu.go
editor/screen.go
editor/tooltip.go
editor/window.go
editor/workspace.go
util/utils.go

This PR allows you to specify letter spacing. However, if letter spacing is specified, Ligature will be forced to be disabled.
* To set it in Settings.toml
``` toml
[Editor]
Letterspace = 0.5
```
* Command
`GoneovimLetterspacing 0.5`
* Settings in init.vim
The command is defined after the start of Goneovim, so if you want to write the settings in `init.vim`, etc., you can directly rpcnotify.
``` vim
call rpcnotify(0, "Gui", "gonvim_letter_spacing", 0.5)
```

Add support letter spacing

---

editor/workspace.go

When Goneovim is installed into a non-writable directory, Goneovim is unusable because helptags cannot be written. Ignore errors to make Goneovim usable.
I created this PR without testing locally, as compiling Goneovim takes a lot of time.

Ignore errors when creating helptags

---

editor/editor.go
editor/workspace.go
runtime/doc/goneovim.txt

Extended the wsl option to allow specifying a distribution other than the default.
For example, for `Debian`, set `--wsl=Debian`.

Accept alternative WSL distribution

---

.github/workflows/release.yaml

The nightly version will be released without a new commit, so the same version will release binaries with different hashes.
Therefore, it may not be possible to update the version with scoop.
So I added a job to check the log date because the release workflow works once a day.

improve: prevent redundant nightly release

---

.github/workflows/release.yaml

In cron, `workflow_dispatch/inputs/tag_name` is not set to default `nightly`, so use `event_name` instead.
> Run test '{ "" == "nightly" && 0 -lt $(git log --oneline --since "yesterday" | wc -l) } || { "" != "nightly" }'
https://github.com/akiyosi/goneovim/runs/6151160847?check_suite_focus=true

fix: prevent redundant scheduled release

---

.github/workflows/release.yaml

The following two have been fixed.
- test command condition
- exclude `.github`, `.gitignore`, `.golangci.yml` when checking commits
This is the result of an action on a time-adjusted commit with `git commit --date='2 days ago'`.
https://github.com/shiena/goneovim/runs/6224173841?check_suite_focus=true

Fix new-commit-check condition

---

cmd/goneovim/main.go
editor/editor.go

Related to #320, detach from terminal by default when Goneovim starts, and leave existing behavior as --nofork option.

Run application in the background and support --nofork option

---

.github/workflows/release.yaml

Fixed publish for nightly builds.
https://github.com/akiyosi/goneovim/runs/7780091328?check_suite_focus=true

fix: release job

---

editor/editor.go

Resolves problems associated with maximizing windows with `WindowGeometryBasedOnFontmetrics` setting enabled.
Related to #373

Improved window maximizing

---

editor/config.go
editor/cursor.go
editor/editor.go
editor/font.go
editor/imetooltip.go
editor/message.go
editor/minimap.go
editor/popupmenu.go
editor/screen.go
editor/tabline.go
editor/tooltip.go
editor/window.go
editor/workspace.go
runtime/doc/goneovim.txt

This PR allows font fallback on a per character basis rather than per font-family basis.
This feature is enabled by the following settings
```
[Editor]
#...
ManualFontFallback = true
```

Add support manual font fallback

---

editor/window.go

This pull request includes a commit that adds functionality to convert Windows paths to Unix paths when running under Windows Subsystem for Linux (WSL). This is achieved by replacing backslashes with forward slashes and converting the drive letter to the corresponding `/mnt/<drive-letter>` format. This enhancement ensures that file paths are correctly handled when running the software under WSL.
fixes  #548

Convert Windows paths to WSL paths when running under WSL

---

editor/input.go

Add Hyper_L/R to the list of non-input keys

---

editor/editor.go
editor/workspace.go

__Problem__:
Goneovim crashes if `:GonvimResize` argument is either of wrong type (e.g. `int64` instead of `string`) or not well formed, as mentioned in #592. Therefore, these commands will leads to a crash:
```vim
:GonvimResize 1
:GonvimResize ""
```
__Solution__:
Add checks before and while executing the Go function associated to `:GonvimResize`:
- ensure that the argument is a string;
- ensure that this string is successfully parsed.

fix: avoid crash caused by GonvimResize argument

---

editor/screen.go

Neovim 0.11.3 can emit msg_set_pos events for grid id 0, which leaves a
“zombie” message row and hides the statusline (see neovide/neovide#3150).
This change ignores msg_set_pos when gridid == 0.
Safe because real message grids use a non-zero id.

workaround: ignore msg_set_pos with grid id 0 (fix hidden statusline)

---

editor/config.go
editor/editor.go
editor/editor_darwin.go
editor/editor_unix.go
editor/editor_windows.go
runtime/doc/goneovim.txt

Adds new configurations: `NativeTitleBarBackgroundColor`, `NativeTitleBarTextColor`.
Now goneovim can have titlebar of any color! This is dark one.
Windows only.
Close #609.

Add customization of native title bar colors on Windows 11

---

editor/config.go
editor/editor.go
editor/nvim.go
editor/workspace.go

This PR introduces the `GonvimFocus` command to bring the goneovim main window to the foreground.
It ensures that the window is shown, raised, and requested to take focus, even if minimized or inactive.
Related to #610

Add GonvimFocus command to activate and raise the main window
